CALL manage_products('Create', NULL, 'Arroz 1kg', 'Arroz blanco de grano largo', 2.50, 100);
CALL manage_products('Create', NULL, 'Leche Entera 1L', 'Leche entera pasteurizada', 1.30, 200);
CALL manage_products('Create', NULL, 'Pan Integral 500g', 'Pan integral en rodajas', 2.00, 150);
CALL manage_products('Create', NULL, 'Aceite de Girasol 1L', 'Aceite de girasol refinado', 3.00, 120);
CALL manage_products('Create', NULL, 'Huevos 12 unidades', 'Docena de huevos frescos', 1.80, 300);
CALL manage_products('Create', NULL, 'Azúcar 1kg', 'Azúcar refinada blanca', 1.20, 250);
CALL manage_products('Create', NULL, 'Sal 500g', 'Sal fina yodada', 0.80, 400);
CALL manage_products('Create', NULL, 'Café Molido 250g', 'Café molido de tueste medio', 4.50, 80);
CALL manage_products('Create', NULL, 'Pasta Espagueti 500g', 'Pasta de espagueti de trigo', 1.50, 180);
CALL manage_products('Create', NULL, 'Jugo de Naranja 1L', 'Jugo de naranja natural', 2.20, 150);
